### PR TITLE
Tickets/dm 27690

### PR DESCRIPTION
**Pull request by menanteau**

### CODE REVIEW

**Comment by menanteau** [comment]
This pull request is to merge the changes from the v2.5.3 branch (DM-27690) back into master.

**Review by srp3rd — COMMENTED** [review]
These changes all look fine.

**Review by srp3rd — APPROVED** [review]
All these changes look fine.  Approved.

**Comment by menanteau** [comment]
Merging branch with 2.5.3.x for AT back into master

**Pull request merged**
