### PR TITLE
Updates to ATHS CCDTEMP keyword

### PR DESCRIPTION
**Pull request by menanteau**

### CODE REVIEW

**Comment by timj** [comment]
Why are we merging master into a ticket branch? That's not the usual DM policy.

**Comment by menanteau** [comment]
> Why are we merging master into a ticket branch? That's not the usual DM policy.

I'm updating this branch to be able to test properly on this branch.

**Comment by timj** [comment]
Policy is to do that by rebasing though.

**Comment by menanteau** [comment]
> Policy is to do that by rebasing though.

You mean 
```git rebase -i master ```

**Comment by timj** [comment]
`git rebase master` is enough assuming your local master is up to date.

```
$ git checkout master
$ git pull
$ git checkout tickets/DM-28518
$ git rebase master
$ git push -f
```

see https://developer.lsst.io/work/flow.html?highlight=rebase#pushing-code

**Review by srp3rd — APPROVED** [review]
The changes look fine.

**Pull request merged**
