### PR TITLE
Update to read telemetry from external file.

### PR DESCRIPTION
**Pull request by menanteau**
Update to CC Telemetry configuration and order of updates.
Adding more json files to library

### CODE REVIEW

**Comment by mareuter** [comment]
I don't see any indication that the HS is in simulation mode with this. The simulation mode construct that salobj provides handles this for you. https://ts-salobj.lsst.io/salobj_cscs.html#simulation-mode

**Comment by menanteau** [comment]
> I don't see any indication that the HS is in simulation mode with this. The simulation mode construct that salobj provides handles this for you. https://ts-salobj.lsst.io/salobj_cscs.html#simulation-mode

Updated to include `hs_simulation_mode` as a configurable option

**Comment by mareuter** [comment]
The logging is nice, but you aren't sending out `logevent_simulationMode` with the `mode` attribute set to a non-zero number. That's the requirement that's missing.

**Comment by menanteau** [comment]
> The logging is nice, but you aren't sending out `logevent_simulationMode` with the `mode` attribute set to a non-zero number. That's the requirement that's missing.

Added `simulationMode` event at startup.

**Review by mareuter — APPROVED** [review]
Looks good to me.

**Pull request merged**
